// PostsReducer Actions. (X, X_PENDING, X_FULFILLED) handled
// by redux-promise-middleware.

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';

export const FETCH_CATEGORY_POSTS = 'FETCH_CATEGORY_POSTS';
export const FETCH_CATEGORY_POSTS_PENDING = 'FETCH_CATEGORY_POSTS_PENDING';
export const FETCH_CATEGORY_POSTS_FULFILLED = 'FETCH_CATEGORY_POSTS_FULFILLED';

export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL';
export const FETCH_POST_DETAIL_PENDING = 'FETCH_POST_DETAIL_PENDING';
export const FETCH_POST_DETAIL_FULFILLED = 'FETCH_POST_DETAIL_FULFILLED';

export const VOTE_POST = 'VOTE_POST';
export const VOTE_POST_PENDING = 'VOTE_POST_PENDING';
export const VOTE_POST_FULFILLED = 'VOTE_POST_FULFILLED';

export const ORDER_POSTS_BY = 'ORDER_POSTS_BY';
export const ORDER_POSTS_BY_PENDING = 'ORDER_POSTS_BY_PENDING';
export const ORDER_POSTS_BY_FULFILLED = 'ORDER_POSTS_BY_FULFILLED';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_PENDING = 'GET_CATEGORIES_PENDING';
export const GET_CATEGORIES_FULFILLED = 'GET_CATEGORIES_FULFILLED';

// PostsReducer Actions: Handled by Redux Thunk

export const CREATE_POST = 'CREATE_POST';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';

// CommentsReducer Actions. (X, X_PENDING, X_FULFILLED) handled
// by redux-promise-middleware.

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_PENDING = 'FETCH_COMMENTS_PENDING';
export const FETCH_COMMENTS_FULFILLED = 'FETCH_COMMENTS_FULFILLED';

export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENT_PENDING = 'FETCH_COMMENT_PENDING';
export const FETCH_COMMENT_FULFILLED = 'FETCH_COMMENT_FULFILLED';

export const VOTE_COMMENT = 'VOTE_COMMENT';
export const VOTE_COMMENT_PENDING = 'VOTE_COMMENT_PENDING';
export const VOTE_COMMENT_FULFILLED = 'VOTE_COMMENT_FULFILLED';

// CommentsReducer Actions: Handled by Redux Thunk

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_FULFILLED = 'CREATE_COMMENT_FULFILLED';
export const TOGGLE_COMMENT_EDIT = 'TOGGLE_COMMENT_EDIT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
